config/routes.rb
# config/routes.rb
Rails.application.routes.draw do
  root 'alphablog#index'
  get 'about', to: 'alphablog#about'
  resources :articles
  resources :bookings, only: [:show, :index, :edit, :update]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  validates :title, presence: true, length: { minimum: 6, maximum: 100 }
  validates :description, presence: true, length: { minimum: 10, maximum: 4096 }
  validates :created_by, presence: true, length: {minimum: 3, maximum: 50}
  validates :updated_by, presence: true, length: {minimum: 3, maximum: 50}
end

app/models/booking.rb
class Booking < ApplicationRecord
  
end

app/controllers/alphablog_controller.rb
# app/controllers/alphablog_controller.rb
class AlphablogController < ApplicationController

  def index
  end

  def about
  end
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

  def show
    @article = Article.find(params[:id])
  end
  
  def index
    @articles = Article.all
  end
  
  def new
    @article = Article.new
    # render plain: params[:article]
  end
  
  def edit
    @article = Article.find(params[:id])
  end
  
  def create
    # render plain: params[:article]
    @article = Article.new(params.require(:article).permit(:title, :description, :created_by, :updated_by))
    if @article.save
      flash[:notice] = "Article was created successfully"
      redirect_to @article
    else
      render 'new'
    end
  end
  
  def update
    @article = Article.find(params[:id])
    if @article.update(params.require(:article).permit(:title, :description, :created_by, :updated_by))
      flash[:notice] = "Article was updated successfully."
      redirect_to @article
    else
      render 'edit'
    end
  end
  
  def destroy
    @article = Article.find(params[:id])
    @article.destroy
    redirect_to articles_path
    
  end

end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController

  def show
    @booking = Booking.find(params[:id])
  end
  
  def index
    @bookings = Booking.all
  end
  
  def edit
    @booking = Booking.find(params[:id])
  end
  
  def update
    @booking = Booking.find(params[:id])
    if @booking.update(params.require(:booking).permit(:guestname, :checkin, :checkout, :price))
      flash[:notice] = "Booking was updated successfully."
      redirect_to @booking
    else
      render 'edit'
    end
  end
  
end

app/helpers/alphablog_helper.rb
module AlphablogHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/alphablog/about.html.erb
<h1>ABOUT PAGE</h1>

app/views/alphablog/index.html.erb
<h1>INDEX PAGE</h1>

<p><%= link_to "Articles list", articles_path %></p>

app/views/articles/create.html.erb
<h1 id="create_new_article_page">CREATE NEW ARTICLE PAGE</h1>


  

app/views/articles/edit.html.erb
<h1 id="edit_article">EDIT ARTICLE</h1>

<% if @article.errors.any?  %>
	<h2>The following errors prevented the article from beeing saved!</h2>
	<ul>
		<% @article.errors.full_messages.each do |msg|  %>
			<li><%= msg %></li>
		<% end %>
	</ul>
<% end  %>

<%= form_with(model: @article, local: true) do |f| %>

	<p>
		<%= f.label :title %><br>
		<%= f.text_field :title %>
	</p>
	<p>
		<%= f.label :description %><br>
		<%= f.text_area :description %>
	</p>
	<p>
		<%= f.label :created_by %><br>
		<%= f.text_field :created_by %>
	</p>
	<p>
		<%= f.label :updated_by %><br>
		<%= f.text_field :updated_by %>
	</p>
	
	<p>
		<%= f.submit %>
	</p>
	
<% end  %>

<p><%= link_to "Return to articles list", articles_path %></p>

app/views/articles/index.html.erb
<h1 id="articles_listing_page">ARTICLES LISTING PAGE</h1>

<table>
	<caption><h2>Articles</h2></caption>
	<thead>
		<tr>
			<th scope="col">Title</th>
			<th scope="col">Description</th>
			<th scope="col">Created by</th>
			<th scope="col">Updated by</th>
			<th colspan="3" scope="col">Actions</th>
		</tr>
	</thead>
	<tbody>
		<% @articles.each do |article| %>
		<tr>
			<td><%= article.title %></td>
			<td><%= article.description %></td>
			<td><%= article.created_by %></td>
			<td><%= article.updated_by %></td>
			<td><%= link_to "Show", article_path(article) %></td>
			<td><%= link_to "Edit", edit_article_path(article) %></td>
			<td>
				<%= link_to "Delete", 
					article_path(article), 
					method: :delete, 
					data: { confirm: "Are you sure?" } %>
			</td>
		</tr>
		<% end %>
	</tbody>
</table>

<p><%= link_to "Create new article", new_article_path %></p>

app/views/articles/new.html.erb
<h1 id="create_a_new_article">CREATE A NEW ARTICLE</h1>

<% if @article.errors.any?  %>
	<h2>The following errors prevented the article from beeing saved!</h2>
	<ul>
		<% @article.errors.full_messages.each do |msg|  %>
			<li><%= msg %></li>
		<% end %>
	</ul>
<% end  %>

<%= form_with scope: :article, url: articles_path, local: true do |f| %>

	<p>
		<%= f.label :title %><br>
		<%= f.text_field :title %>
	</p>
	<p>
		<%= f.label :description %><br>
		<%= f.text_area :description %>
	</p>
	<p>
		<%= f.label :created_by %><br>
		<%= f.text_field :created_by %>
	</p>
	<p>
		<%= f.label :updated_by %><br>
		<%= f.text_field :updated_by %>
	</p>
	
	<p>
		<%= f.submit %>
	</p>
	
<% end  %>
<p><%= link_to "Return to articles list", articles_path %></p>

app/views/articles/show.html.erb
<h1>SHOW ARTICLE DETAILS</h1>

<p><strong>Title: </strong><%= @article.title %></p>
<p><strong>Description: </strong><%= @article.description %></p>
<p><strong>Created by: </strong><%= @article.created_by %></p>
<p><strong>Updated by: </strong><%= @article.updated_by %></p>

<p>
	<%= link_to "Edit", edit_article_path(@article) %> |
	<%= link_to "Delete", article_path(@article), method: :delete, data: { confirm: "Are you sure?"} %> |
	<%= link_to "Return to articles list", articles_path %>
</p>

app/views/bookings/edit.html.erb
<h1 id="edit_booking">EDIT BOOKING</h1>

<% if @booking.errors.any?  %>
	<h2>The following errors prevented the booking from beeing saved!</h2>
	<ul>
		<% @booking.errors.full_messages.each do |msg|  %>
			<li><%= msg %></li>
		<% end %>
	</ul>
<% end  %>

<%= form_with(model: @booking, local: true) do |f| %>

	<p>
		<%= f.label :guestname %><br>
		<%= f.text_field :guestname %>
	</p>
	<p>
		<%= f.label :checkin %><br>
		<%= f.text_field :checkin %>
	</p>
	<p>
		<%= f.label :checkout %><br>
		<%= f.text_field :checkout %>
	</p>
	<p>
		<%= f.label :price %><br>
		<%= f.text_field :price %>
	</p>
	
	<p>
		<%= f.submit %>
	</p>
	
<% end  %>

<p><%= link_to "Return to bookings list", bookings_path %></p>

app/views/bookings/index.html.erb
<h1 id="bookings_listing_page">BOOKINGS LISTING PAGE</h1>

<table>
	<caption><h2>Bookings</h2></caption>
	<thead>
		<tr>
			<th scope="col">Guest</th>
			<th scope="col">Check-In-Date</th>
			<th scope="col">Check-Out-Date</th>
			<th scope="col">Price</th>
			<th colspan="3" scope="col">Actions</th>
		</tr>
	</thead>
	<tbody>
		<% @bookings.each do |booking| %>
		<tr>
			<td><%= booking.guestname %></td>
			<td><%= booking.checkin %></td>
			<td><%= booking.checkout %></td>
			<td><%= booking.price %> €</td>
			<td><%= link_to "Show", booking_path(booking) %></td>
			<td><%= link_to "Edit", edit_booking_path(booking) %></td>
		</tr>
		<% end %>
	</tbody>
</table>

app/views/bookings/show.html.erb
<h1>SHOW BOOKING DETAILS</h1>

<p><strong>Guestname: </strong><%= @booking.guestname %></p>
<p><strong>Check-In: </strong><%= @booking.checkin %></p>
<p><strong>Check-Out: </strong><%= @booking.checkout %></p>
<p><strong>Price: </strong><%= @booking.price %></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>UbAlphaBlog6</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
		<% flash.each do |k, v| %>
			<%= v %>
		<% end %>
    <%= yield %>
  </body>
</html>